const courses = [
  {
    title: "Precision and Accuracy",
    teacher: "By: M S Nawaz",
    description: `Court training is where we fine-tune our shots for precision and accuracy. From mastering the perfect drop shot to perfecting your smashes, our coaches will guide you through drills and exercises to sharpen your technique.`,
    image: "./assets/images/course-img1.jpg",
    date: "02.03.2010",
    shows: "65",
    comments: "23",
    alias: "precision-and-accuracy",
    rating: "4",
  },

  {
    title: "Strength and Endurance",
    teacher: "By: Subas Das",
    description: `Badminton is not just about quick reflexes; it's also about endurance and strength. Our court training includes targeted exercises to build the stamina and power needed to dominate the court from the first serve to the final point.`,
    image: "./assets/images/course-img2.jpg",
    date: "02.03.2012",
    shows: "65",
    comments: "23",
    alias: "strength-and-endurance",
    rating: "3",
  },

  {
    title: "Strength Training",
    teacher: "By: Mr Junaid Juvaid",
    description: `Develop the muscular power needed for powerful smashes and quick movements on the court. Our strength training sessions are tailored to target key muscle  essential for badminton players.`,
    image: "./assets/images/course-img3.jpg",
    date: "02.03.2015",
    shows: "65",
    comments: "23",
    alias: "strength-training",
    rating: "4",
  },

  {
    title: "Agility and Flexibility",
    teacher: "By: Mr Mohammed Haitam",
    description: `Badminton is a sport that demands quick, precise movements. Badminton Fit focuses on improving agility and flexibility through dynamic exercises, helping you manoeuvre around the court with ease.`,
    image: "./assets/images/badminton-card.jpg",
    date: "22.02.2002",
    shows: "65",
    comments: "23",
    alias: "agility-and-flexibility",
    rating: "4",
  },

  {
    title: "Cardiovascular Endurance",
    teacher: "By: Mr Mohammed",
    description: `Enhance your stamina for longer rallies and intense matches. Our cardiovascular workouts are designed to increase endurance, ensuring you stay energized from the first serve to the final point.`,
    image: "./assets/images/badminton-card.jpg",
    date: "22.02.2002",
    shows: "65",
    comments: "23",
    alias: "cardiovascular-endurance",
    rating: "4",
  },

  {
    title: "Balance and Coordinatio",
    teacher: "By: Mr Mohammed Zayan",
    description: `Mastering the art of badminton requires impeccable balance and coordination. Badminton Fit incorporates drills and exercises to fine-tune your motor skills, leading to better on-court performance.`,
    image: "./assets/images/badminton-card.jpg",
    date: "28.05.2013",
    shows: "65",
    comments: "23",
    alias: "balance-and-coordinatio",
    rating: "5",
  },
];
